country = Spree::Country.find_by(name: 'Россия')

Spree::State.create!([
  { name: 'Республика Адыгея', abbr: 'RU-AD', country: country  },
  { name: 'Республика Башкортостан', abbr: 'RU-BA', country: country  },
  { name: 'Республика Бурятия', abbr: 'RU-BU', country: country  },
  { name: 'Республика Алтай', abbr: 'RU-AL', country: country  },
  { name: 'Республика Дагестан', abbr: 'RU-DA', country: country  },
  { name: 'Республика Ингушетия', abbr: 'RU-IN', country: country  },
  { name: 'Кабардино-Балкарская республика', abbr: 'RU-KB', country: country  },
  { name: 'Республика Калмыкия', abbr: 'RU-KL', country: country  },
  { name: 'Карачаево-Черкесская республика', abbr: 'RU-KC', country: country  },
  { name: 'Республика Карелия', abbr: 'RU-KR', country: country  },
  { name: 'Республика Коми', abbr: 'RU-KO', country: country  },
  { name: 'Республика Марий Эл', abbr: 'RU-ME', country: country  },
  { name: 'Республика Мордовия', abbr: 'RU-MO', country: country  },
  { name: 'Республика Саха (Якутия)', abbr: 'RU-SA', country: country  },
  { name: 'Республика Северная Осетия — Алания', abbr: 'RU-SE', country: country  },
  { name: 'Республика Татарстан', abbr: 'RU-TA', country: country  },
  { name: 'Республика Тыва', abbr: 'RU-TY', country: country  },
  { name: 'Удмуртская республика', abbr: 'RU-UD', country: country  },
  { name: 'Республика Хакасия', abbr: 'RU-KK', country: country  },
  { name: 'Чеченская республика', abbr: 'RU-CE', country: country  },
  { name: 'Чувашская республика', abbr: 'RU-CU', country: country  },
  { name: 'Алтайский край', abbr: 'RU-ALT', country: country  },
  { name: 'Забайкальский край', abbr: 'RU-ZAB', country: country  },
  { name: 'Камчатский край', abbr: 'RU-KAM', country: country  },
  { name: 'Краснодарский край', abbr: 'RU-KDA', country: country  },
  { name: 'Красноярский край', abbr: 'RU-KIA', country: country  },
  { name: 'Пермский край', abbr: 'RU-PER', country: country  },
  { name: 'Приморский край', abbr: 'RU-PRI', country: country  },
  { name: 'Ставропольский край', abbr: 'RU-STA', country: country  },
  { name: 'Хабаровский край', abbr: 'RU-KHA', country: country  },
  { name: 'Амурская область', abbr: 'RU-AMU', country: country  },
  { name: 'Архангельская область', abbr: 'RU-ARK', country: country  },
  { name: 'Астраханская область', abbr: 'RU-AST', country: country  },
  { name: 'Белгородская область', abbr: 'RU-BEL', country: country  },
  { name: 'Брянская область', abbr: 'RU-BRY', country: country  },
  { name: 'Владимирская область', abbr: 'RU-VLA', country: country  },
  { name: 'Волгоградская область', abbr: 'RU-VGG', country: country  },
  { name: 'Вологодская область', abbr: 'RU-VLG', country: country  },
  { name: 'Воронежская область', abbr: 'RU-VOR', country: country  },
  { name: 'Ивановская область', abbr: 'RU-IVA', country: country  },
  { name: 'Иркутская область', abbr: 'RU-IRK', country: country  },
  { name: 'Калининградская область', abbr: 'RU-KGD', country: country  },
  { name: 'Калужская область', abbr: 'RU-KLU', country: country  },
  { name: 'Кемеровская область', abbr: 'RU-KEM', country: country  },
  { name: 'Кировская область', abbr: 'RU-KIR', country: country  },
  { name: 'Костромская область', abbr: 'RU-KOS', country: country  },
  { name: 'Курганская область', abbr: 'RU-KGN', country: country  },
  { name: 'Курская область', abbr: 'RU-KRS', country: country  },
  { name: 'Ленинградская область', abbr: 'RU-LEN', country: country  },
  { name: 'Липецкая область', abbr: 'RU-LIP', country: country  },
  { name: 'Магаданская область', abbr: 'RU-MAG', country: country  },
  { name: 'Московская область', abbr: 'RU-MOS', country: country  },
  { name: 'Мурманская область', abbr: 'RU-MUR', country: country  },
  { name: 'Нижегородская область', abbr: 'RU-NIZ', country: country  },
  { name: 'Новгородская область', abbr: 'RU-NGR', country: country  },
  { name: 'Новосибирская область', abbr: 'RU-NVS', country: country  },
  { name: 'Омская область', abbr: 'RU-OMS', country: country  },
  { name: 'Оренбургская область', abbr: 'RU-ORE', country: country  },
  { name: 'Орловская область', abbr: 'RU-ORL', country: country  },
  { name: 'Пензенская область', abbr: 'RU-PNZ', country: country  },
  { name: 'Псковская область', abbr: 'RU-PSK', country: country  },
  { name: 'Ростовская область', abbr: 'RU-ROS', country: country  },
  { name: 'Рязанская область', abbr: 'RU-RYA', country: country  },
  { name: 'Самарская область', abbr: 'RU-SAM', country: country  },
  { name: 'Саратовская область', abbr: 'RU-SAR', country: country  },
  { name: 'Сахалинская область', abbr: 'RU-SAK', country: country  },
  { name: 'Свердловская область', abbr: 'RU-SVE', country: country  },
  { name: 'Смоленская область', abbr: 'RU-SMO', country: country  },
  { name: 'Тамбовская область', abbr: 'RU-TAM', country: country  },
  { name: 'Тверская область', abbr: 'RU-TVE', country: country  },
  { name: 'Томская область', abbr: 'RU-TOM', country: country  },
  { name: 'Тульская область', abbr: 'RU-TUL', country: country  },
  { name: 'Тюменская область', abbr: 'RU-TYU', country: country  },
  { name: 'Ульяновская область', abbr: 'RU-ULY', country: country  },
  { name: 'Челябинская область', abbr: 'RU-CHE', country: country  },
  { name: 'Ярославская область', abbr: 'RU-YAR', country: country  },
  { name: 'Москва', abbr: 'RU-MOW', country: country  },
  { name: 'Санкт-Петербург', abbr: 'RU-SPE', country: country  },
  { name: 'Еврейская автономная область', abbr: 'RU-YEV', country: country  },
  { name: 'Ненецкий автономный округ', abbr: 'RU-NEN', country: country  },
  { name: 'Ханты-Мансийский автономный округ - Югра', abbr: 'RU-KHM', country: country  },
  { name: 'Чукотский автономный округ', abbr: 'RU-CHU', country: country  },
  { name: 'Ямало-Ненецкий автономный округ', abbr: 'RU-YAN', country: country  }
])
